config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  # # create
  # get 'movies/new'
  # post 'movies/create'#correct

  
  # # update
  # get 'movies/edit'#correct
  # put 'movies/update'#
  # patch 'movies/update'

  # # Read
  # get 'movies/index', to: 'movies#index'
  # get 'movies/:id/show', to: 'movies#show'

  # #delete
  # delete 'movies/destroy'

  get "movies", to:"movies#index"
  post "movies",to:"movies#create"
  get "movies/new",to: "movies#new", as: "new_movie"
  get "movies/:id/edit",to:"movies#edit", as: "edit_movie"
  get "movies/:id",to:"movies#show", as: "movie"
  put "movies/:id",to:"movies#update"
  patch "movies/:id",to:"movies#update"
  delete "movies/:id", to:"movies#destroy", as:"delete_movie"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    
  end

  def create #done
    # render json: params
    @movie = Movie.new(movie_params)
    @movie.save
    
    # redirect_to @movie
    redirect_to movie_path(@movie.id)
  end

  private def movie_params
    params.require(:movie).permit(:title,:release_date,:genre,:raintime,:image)

    
  end

  def new #done
    @movie = Movie.new
  end

  def edit 
    @movie = Movie.find(params[:id])
    
  end

  def update
    # render json:params
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)

    redirect_to @movie
  end

  def destroy
    # render json: params
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to movies_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :content, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BolyFilms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%=form_with model:movie, local:true do |form|%>
    <p>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </p>

    <p>
        <%= form.label :genre%>
        <%= form.text_field :genre%>
    </p>

    <p>
        <%= form.label :runtime%>
        <%= form.text_field :runtime, type:"number"%>
    </p>

    <p>
        <%= form.label :release_date%>
        <%= form.text_field :release_date, type: "date"%>
    </p>

    <p>
        <%= form.label :image%>
        <%= form.text_field :image%>
    </p>

    <%= form.submit "Update Movie"%>

<%end%>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'form',movie: @movie%>

app/views/movies/index.html.erb
<h1>Movies</h1>
<%= link_to "New Movie", new_movie_path%>
<br><br>

<%@movies.each do |movie|%>
    <div>
        <%=movie.inspect%>
        <%= link_to "Edit",edit_movie_path(movie)%>
        <%= link_to "Delete Movie", delete_movie_path(movie), method: :delete, data: {confirm: "Are yo usure"}%>
    </div>
<%end%>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<%= form_with model:@movie, local:true do |form|%>
    <p>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </p>

    <p>
        <%= form.label :genre%>
        <%= form.text_field :genre%>
    </p>

    <p>
        <%= form.label :runtime%>
        <%= form.text_field :runtime, type:"number"%>
    </p>

    <p>
        <%= form.label :release_date%>
        <%= form.text_field :release_date, type: "date"%>
    </p>

    <%= form.submit "Save Movie"%>

<%end%>

app/views/movies/show.html.erb
<%=@movie.inspect%>

<%= image_tag(@movie.image)%>
<%=link_to "Movies", movies_path%>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Content</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.content %></td>
        <td><%= review.author %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @review.author %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>